"""
Generate LaTeX tables from the numerical experiment CSV files.

This script is part of the reproducibility package for the paper

    Exact Finite-Horizon Memory, Conditioning, and Dissipative
    Decay in Coarse Upwind Finite-Volume Prediction

It should be run after `run_experiments.py`, which produces the CSV files in
the `results/` directory.  This script reads those CSV files and writes small
LaTeX table fragments into the `tables/` directory.  The generated `.tex`
files can be included directly in the manuscript with `\\input{...}`.

Inputs
------
The script expects the following files to already exist:

    results/rank_effective.csv
        Produced by the rank/effective-rank experiment.  It contains, for
        each Courant number lambda and horizon L, the exact rank formula, the
        effective SVD rank, the SVD tolerance, and selected singular-value
        diagnostics.

    results/step_flattening.csv
        Produced by the periodic step-function flattening experiment.  It
        contains the time history of the mean, L2 deviation from the mean,
        Linf deviation from the mean, periodic total variation, mean drift,
        and the diagnostic theoretical E2 bound.

    results/flux_closure_check.csv
        Produced by the one-step flux-closure verification check.  It
        contains the maximum parent-average discrepancy for each random
        trial.

Outputs
-------
The script writes:

    tables/rank_saturation_table.tex
        A compact LaTeX table reporting the exact rank, effective rank, and
        SVD tolerance at the saturated horizon L = r - 1.  In the experiments
        used in the paper, P = 8, r = 6, so the saturated horizon is L = 5.

    tables/step_final_table.tex
        A compact LaTeX table reporting final diagnostics for the
        step-function experiment: final E2, final Einf, final total
        variation, and the maximum mean drift over the run.

The script also prints to the terminal:

    Flux closure summary
        The maximum and mean discrepancies over all random trials in
        `results/flux_closure_check.csv`.

How to run
----------
From the repository root, run:

    python run_experiments_v4.py
    python make_tables.py

The first command creates the files in `results/`.  The second command,
this script, creates the files in `tables/`.

Notes
-----
This script does not rerun any numerical experiment.  It only post-processes
CSV files generated by `run_experiments.py`.

The LaTeX fragments written here contain only the `tabular` environments,
not the surrounding `table` environments.  This allows the manuscript to
supply captions, labels, and placement options separately.

Important: if experiment parameters are changed in `run_experiments.py`,
especially the saturated horizon or the list of Courant numbers, check that
the hard-coded selection `L == 5` in `make_rank_saturation_table()` still
corresponds to `L = r - 1`.
"""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Dict, List


def ensure_dir() -> None:
    Path("tables").mkdir(exist_ok=True)


def sci(x: float) -> str:
    if x == 0.0:
        return r"$0$"
    return rf"${x:.3e}$"


def make_rank_saturation_table() -> None:
    path = Path("results/rank_effective.csv")
    rows: List[Dict[str, str]] = []

    with path.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            if int(row["L"]) == 5:
                rows.append(row)

    rows.sort(key=lambda r: float(r["lambda"]), reverse=True)

    out = Path("tables/rank_saturation_table.tex")
    with out.open("w") as f:
        f.write(r"\begin{tabular}{@{}cccc@{}}" + "")
        f.write(r"\toprule" + "")
        f.write(r"$\lambda$ & exact rank & effective rank & tolerance $\tau$ \$" + "")
        f.write(r"\midrule" + "")

        for row in rows:
            lam = float(row["lambda"])
            exact_rank = int(row["exact_rank_formula"])
            eff_rank = int(row["effective_rank"])
            tau = float(row["tau"])
            f.write(rf"${lam:g}$ & {exact_rank} & {eff_rank} & {sci(tau)} \$" + "")

        f.write(r"\bottomrule" + "")
        f.write(r"\end{tabular}" + "")


def make_step_final_table() -> None:
    path = Path("results/step_flattening.csv")

    data: Dict[float, List[Dict[str, str]]] = {}
    with path.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            lam = float(row["lambda"])
            data.setdefault(lam, []).append(row)

    out = Path("tables/step_final_table.tex")
    with out.open("w") as f:
        f.write(r"\begin{tabular}{@{}ccccc@{}}" + "")
        f.write(r"\toprule" + "")
        f.write(
            r"$\lambda$ & final $E_2$ & final $E_\infty$ & final TV & max mean drift \$"+ ""
        )
        f.write(r"\midrule" + "")

        for lam in sorted(data.keys(), reverse=True):
            rows = data[lam]
            final = max(rows, key=lambda r: int(r["n"]))
            max_drift = max(float(r["mean_drift"]) for r in rows)

            f.write(
                rf"${lam:g}$ & "
                rf"{sci(float(final['E2']))} & "
                rf"{sci(float(final['Einf']))} & "
                rf"{sci(float(final['TV']))} & "
                rf"${sci(max_drift)} \$"+ "")

        f.write(r"\bottomrule" + "")
        f.write(r"\end{tabular}" + "")


def print_flux_closure_summary() -> None:
    path = Path("results/flux_closure_check.csv")
    vals = []

    with path.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            vals.append(float(row["max_abs_error"]))

    print("Flux closure summary")
    print("  max discrepancy:", max(vals))
    print("  mean discrepancy:", sum(vals) / len(vals))


def main() -> None:
    ensure_dir()
    make_rank_saturation_table()
    make_step_final_table()
    print_flux_closure_summary()
    print("Wrote tables to ./tables")


if __name__ == "__main__":
    main()
